### ISSUE TITLE
Abort install on steam discovery after update today

### ISSUE THREAD

**Issue by PokeFan2650** [flathub/com.pokemmo.PokeMMO#11]
Aborted due to failure (Wrong size for extra data https://dl.pokemmo.com/download/PokeMMO-Client.zip)

**Comment by mr-football** [comment]
Same problem here on steam deck. A fix would be great, thanks in advance!

**Comment by spazziale** [comment]
Should be fixed in main, will be online in flathub in few hours

**Comment by mr-football** [comment]
> Should be fixed in main, will be online in flathub in few hours

Thank you very mutch. New version throws a different error now, will check again later..

**Comment by mr-football** [comment]
> > Should be fixed in main, will be online in flathub in few hours
> 
> Thank you very mutch. New version throws a different error now, will check again later..

Everything fine now, thanks!
