### ISSUE TITLE
Freezes when pressing "Import mod" button

### ISSUE THREAD

**Issue by Nevon** [flathub/com.pokemmo.PokeMMO#18]
To reproduce:
1. Press the "mod management" button in the main menu
2. Press the "import mod" button

What happens:
The game freezes. Nothing else happens. The UI remains completely unresponsive. There's nothing interesting in the log after pressing the button.

I'm not entirely sure what the game is actually trying to do here, but I'm assuming it's trying to access something outside of the sandbox, and not handling the error correctly (I could also be completely wrong and this is caused by something else). I tested temporarily giving it `--filesystem=host` but still got the error, so perhaps it's not due to filesystem sandboxing.

**Comment by kyu-n** [comment]
Resolved in #27. For some reason, the game client was picking up zenity as a binary and trying to launch that instead of falling back to native dialogue
